Done count charaters in data.txt file.
Sticky5/Java23 pull request #31
Opened 2021-09-11 23:30 UTC by Sticky5

2021-09-13 05:42 UTC, mtszpater commented on src/main/java/pl/winiarczyk/lesson4/homework/TextFile/CountCharacter.java
> +        String text = Files.readString(Path.of("C:\\Users\\Lenovo\\Java23\\data.txt"));
U mnie ten program nie zadziała, bo nie mam lokalizacji: C:\\Users\Lenovo[...]

Można uniknąc takich problemów - podpowiedź: ścieżka relatywna vs absolutna

2021-09-15 20:53 UTC, MateuszMarczak requested changes

2021-09-15 20:53 UTC, MateuszMarczak commented on src/main/java/pl/winiarczyk/lesson4/homework/TextFile/CountCharacter.java
> +        }
A jak jest różnica w wyliczeniu count a wartości text.lenght()? ;)

2021-09-15 21:15 UTC, Sticky5 commented on src/main/java/pl/winiarczyk/lesson4/homework/TextFile/CountCharacter.java
> +        }
Według mojego założenia text.lenght() ma zwrócić długość liczbową znaków w pliku a count ma za zadanie dodanie każdego znaku z pliku.

2021-09-16 05:50 UTC, MateuszMarczak requested changes

2021-09-16 05:50 UTC, MateuszMarczak commented on src/main/java/pl/winiarczyk/lesson4/homework/TextFile/CountCharacter.java
> +        }
u Ciebie count == text.lenght(), więc po co robić jeszcze pętle?

2021-09-16 13:45 UTC, mtszpater approved these changes

2021-09-16 15:08 UTC, merged